#!/usr/bin/env ruby

def remove_non_module_directories(string)
  string.gsub(/^spec\//, '')
    .gsub(/^lib\//, '')
    .gsub(/^app\//, '')
    .gsub(/^controllers\//, '')
    .gsub(/^views\//, '')
    .gsub(/^models\//, '')
end

def camelize(string)
  string.split(".").first.split("/").map do |substring|
    substring.split("_").map do |subsubstring|
      subsubstring.capitalize
    end.join
  end.join("::")
end

def classify(string)
  camelize(remove_non_module_directories(string))
end

filepath = ARGV[0]
code_filepath =  filepath.gsub("_spec.rb", ".rb")

templates = {
  /app\/config\/initializers/ => '',
  /^spec\/support/ => '',
  /_spec\.rb$/ => <<~SPEC,
  # frozen_string_literal: true

  RSpec.describe #{classify(code_filepath)} do

  end
  SPEC
  /\.rb$/ => <<~RUBY,
  # frozen_string_literal: true

  class #{classify(filepath)}

  end
  RUBY
}


matching_regex = templates.keys.find do |filename_regex|
  filepath[filename_regex]
end

File.write(filepath, templates[matching_regex])
