precmd_functions=()

source $HOME/.dotfiles/aliases.sh
source $HOME/.dotfiles/zsh/utils.sh
source $HOME/.dotfiles/zsh/aliases.sh
source $HOME/.dotfiles/zsh/prompt.sh
source $HOME/.dotfiles/zsh/history.sh
source $HOME/.dotfiles/zsh/vimify.sh
source $HOME/.dotfiles/zsh/mandatory_aliases.sh
source $HOME/.dotfiles/zsh/explicit_aliases.sh

source $HOME/.dotfiles/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH"
PATH=$PATH:/usr/local/bin

# Autojump
[[ -s $HOME/.autojump/etc/profile.d/autojump.sh ]] && source $HOME/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u

# Allow opening a bunch of files
ulimit -n 1024

# Haskell
export PATH="$HOME/Library/Haskell/bin:$PATH"

export EDITOR=vim

setopt AUTO_CD
j # Jump to most commonly used directory

if [ -f $HOME/.dotfiles/local/zshrc ]; then
  source $HOME/.dotfiles/local/zshrc
fi

eval $(docker-machine env default)

source $HOME/.dotfiles/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^ ' autosuggest-accept
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=6'
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+='check-alias-and-accept'
