source $HOME/.dotfiles/aliases.sh
source $HOME/.dotfiles/zsh/utils.sh
source $HOME/.dotfiles/zsh/aliases.sh

PROMPT='%{%F{magenta}%}%n%{%F{default}%}@%{%F{yellow}%}%m%{%F{default}%}:%1~ %# '

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# Autojump
[[ -s $HOME/.autojump/etc/profile.d/autojump.sh ]] && source $HOME/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u

# Allow opening a bunch of files
ulimit -n 1024
